"""Optimizers for models"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_optimizer.ipynb.

# %% auto 0
__all__ = ['Optimizer']

# %% ../nbs/00_optimizer.ipynb 3
import pyswarms as ps
import numpy as np
import pandas as pd

# %% ../nbs/00_optimizer.ipynb 4
class Optimizer:
    
    def __init__(self, model):
        self.model = model
    
